# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://example.com"

theme = "amperage"

pygmentsUseClasses = true

# Number of posts shown per page (dafault: 10)
paginate = 3

# Language sections
[languages]
[languages.en]
contentDir = "content"
description = "This is an demo for AMP!"
languageCode = "en"
languageName = "English"
title = "DrT"
weight = 1
[languages.es]
contentDir = "content/spanish"
description = "Esta es una demo para el tema Amperage!"
languageCode = "es"
languageName = "Español"
title = "AMP Site"
weight = 2

# Menu elements
[[menu.main]]
identifier = "hugo"
name = "About me"
url = "https://gohugo.io"
weight = 8
[[menu.main]]
identifier = "author"
name = "Treatment"
url = "https://asur.dev"
weight = 9
[[menu.main]]
identifier = "github"
name = "Testimonials"
url = "https://github.com/asurbernardo/amperage"
weight = 10
[[menu.main]]
identifier = "github"
name = "Contacts"
url = "https://github.com/asurbernardo/amperage"
weight = 11

# Enable only tags taxonomy
[taxonomies]
tag = "tags"

[params]
copyright = "Amperage" # Name shown on footer copyright
themeColor = "#333" # Theme color displayed on mobile browsers

# Default AMP components for the whole site
ampElements = ["amp-iframe", "amp-analytics", "amp-social-share", "amp-install-serviceworker"]

# Google Analytics code
# googleAnalytics = "UA-xxxxxxxxx-x"

# Adsense publisher code
# adsensePublisher = "ca-pub-123456789"

# Comments Iframe URL
# commentsEmbedUrl = "https://comments.example.com"

# Social sites for metatags
facebookSite = "example"
twitterSite = "@example"

# Structured data elements
socialProfiles = ["https://twitter.com/example", "https://www.linkedin.com/in/example/", "https://github.com/example"]

alternatePageName = "Amperage example"
organizationLogo = "/logo.png"
organizationName = "Asur"

publisherLogo = "/logo-amp-article.png"
publisherLogoHeight = 60
publisherLogoWidth = 600
publisherName = "amperage"

[markup]
defaultMarkdownHandler = "blackfriday"
